# Copyright (c) 2012-2017 Red Hat, Inc
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# This is file is needed to include the project in the CentOS Container
# Pipeline main index. It can be used to set the image name (using job-id), set
# the test script and/or build script and whether to perform or skip the
# user-defined tests. More information on cccp.yml file can be found on:
# https://github.com/CentOS/container-index#the-cccpyml-file

job-id: che-dev
