kind: PersistentVolume
apiVersion: v1
metadata:
  name: che-data-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jonah/pv/che-data-volume"
