kind: PersistentVolume
apiVersion: v1
metadata:
  name: keycloak-data
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jonah/pv/keycloak-data"
